# Generated by Django 3.1.2 on 2020-10-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('owner', models.CharField(max_length=120, null=True)),
                ('admins', models.CharField(max_length=120, null=True)),
                ('members', models.CharField(max_length=120, null=True)),
                ('time_table', models.TextField(null=True)),
            ],
        ),
    ]
