# Generated by Django 3.1.2 on 2020-10-14 08:31

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(default=rooms.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=120)),
                ('details', models.TextField()),
                ('owner', models.CharField(max_length=120)),
                ('admins', models.CharField(blank=True, max_length=120, null=True)),
                ('members', models.CharField(blank=True, max_length=120, null=True)),
                ('time_table', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
