# Generated by Django 3.1.2 on 2020-10-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='time_table',
            new_name='timetable',
        ),
    ]
