# Generated by Django 3.1.2 on 2020-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20201007_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='CB56C2', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
