# Generated by Django 3.1.2 on 2020-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20201008_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='D87584', editable=False, max_length=6),
        ),
    ]
