# Generated by Django 3.1.2 on 2020-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20201008_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='E81010', editable=False, max_length=6),
        ),
    ]
