# Generated by Django 3.1.2 on 2020-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20201008_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='318C2B', editable=False, max_length=6),
        ),
    ]
