# Generated by Django 3.1.2 on 2020-10-08 14:16

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_auto_20201008_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=rooms.models.get_code, editable=False, max_length=6),
        ),
    ]
