# Generated by Django 3.1.2 on 2020-10-09 09:48

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20201009_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=rooms.models.get_code, editable=False, max_length=6),
        ),
    ]
