# Generated by Django 3.1.2 on 2020-10-09 09:52

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_auto_20201009_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=rooms.models.get_code, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
