# Generated by Django 3.1.2 on 2020-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201009_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
